-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS edulink;
USE edulink;

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create colleges table
CREATE TABLE IF NOT EXISTS colleges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  type VARCHAR(100) NOT NULL,
  level VARCHAR(100) NOT NULL,
  ranking INT DEFAULT NULL,
  tuition VARCHAR(100) DEFAULT NULL,
  acceptance VARCHAR(50) DEFAULT NULL,
  students VARCHAR(50) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  established INT DEFAULT NULL,
  programs JSON DEFAULT NULL,
  boardingType VARCHAR(100) DEFAULT NULL,
  showInSchoolList BOOLEAN DEFAULT FALSE,
  showInCollegeList BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create courses table
CREATE TABLE IF NOT EXISTS courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  level VARCHAR(100) NOT NULL,
  duration VARCHAR(100) NOT NULL,
  field VARCHAR(100) NOT NULL,
  ranking INT DEFAULT NULL,
  avgSalary VARCHAR(100) DEFAULT NULL,
  jobGrowth VARCHAR(50) DEFAULT NULL,
  difficulty VARCHAR(100) DEFAULT NULL,
  students VARCHAR(50) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  established VARCHAR(100) DEFAULT NULL,
  careers JSON DEFAULT NULL,
  requirements JSON DEFAULT NULL,
  universities JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create blogs table
CREATE TABLE IF NOT EXISTS blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  excerpt TEXT DEFAULT NULL,
  content TEXT DEFAULT NULL,
  date VARCHAR(100) DEFAULT NULL,
  category VARCHAR(100) NOT NULL,
  image TEXT DEFAULT NULL,
  readTime VARCHAR(50) DEFAULT NULL,
  tags JSON DEFAULT NULL,
  views INT DEFAULT 0,
  likes INT DEFAULT 0,
  comments INT DEFAULT 0,
  author VARCHAR(255) DEFAULT 'Suraj Khadka',
  authorImage TEXT DEFAULT NULL,
  is_featured BOOLEAN DEFAULT TRUE,
  is_recent BOOLEAN DEFAULT FALSE,
  is_new BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
