-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS edulink;
USE edulink;

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create colleges table
CREATE TABLE IF NOT EXISTS colleges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  type VARCHAR(100) NOT NULL,
  level VARCHAR(100) NOT NULL,
  ranking INT DEFAULT NULL,
  tuition VARCHAR(100) DEFAULT NULL,
  acceptance VARCHAR(50) DEFAULT NULL,
  students VARCHAR(50) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  established INT DEFAULT NULL,
  programs JSON DEFAULT NULL,
  boardingType VARCHAR(100) DEFAULT NULL,
  showInSchoolList BOOLEAN DEFAULT FALSE,
  showInCollegeList BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

